
# Generated by Django 5.2.7 on 2025-11-05 05:21

import uuid
from django.db import migrations, models
from django.db.utils import IntegrityError


def populate_unique_emails(apps, schema_editor):
    Profile = apps.get_model('profiles', 'Profile')
    for profile in Profile.objects.filter(email__isnull=True):
        # Genera un email único basado en el ID del usuario y un UUID
        unique_email = f'temp_{profile.user.id}_{uuid.uuid4()}@example.com'
        profile.email = unique_email
        try:
            profile.save()
        except IntegrityError:
            # En caso de una colisión improbable, intenta con un nuevo UUID
            profile.email = f'temp_{profile.user.id}_{uuid.uuid4()}@example.com'
            profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_name_remove_profile_phone_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_unique_emails, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]