# Generated by Django 5.2.8 on 2025-12-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='img/default-profile.png', upload_to='usuarios/fotos'),
        ),
    ]
