# Generated by Django 5.2.7 on 2025-12-03 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_categoria_subcategoria_publicacion_subcategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='subcategoria',
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posting.categoria'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subCategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posting.subcategoria'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
