# Generated by Django 5.2.7 on 2025-12-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_remove_publicacion_subcategoria_articulo_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='condicion',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('USADO', 'Usado')], default='USADO', max_length=10),
        ),
    ]
